#include "ohl/vfs/iso9660_archive.hpp"

#include "ohl/platform/media_source.hpp"
#include "ohl/vfs/media_archive.hpp"

#include "synthetic_media_test_support.hpp"

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <span>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>
#include <vector>

// Every fixture in this file is generated by the project-authored synthetic
// ECMA-119 builder. No byte, name or listing comes from any real medium.

namespace {

using ohl::media::test::SyntheticIso9660Options;
using ohl::vfs::DirectoryEntry;
using ohl::vfs::EntryType;
using ohl::vfs::Iso9660Archive;
using ohl::vfs::MediaArchive;
using ohl::vfs::MediaFormat;
using ohl::vfs::UdfArchiveLimits;
using ohl::vfs::VfsError;

int failures = 0;

void check(const bool condition, const std::string_view context) {
  if (!condition) {
    std::cerr << "failed: " << context << '\n';
    ++failures;
  }
}

class TemporaryDirectory final {
 public:
  TemporaryDirectory() {
    std::error_code error;
    const auto parent = std::filesystem::temp_directory_path(error);
    if (error) {
      return;
    }
    const auto nonce =
        std::chrono::steady_clock::now().time_since_epoch().count();
    for (unsigned int attempt = 0; attempt < 128; ++attempt) {
      auto candidate = parent / ("ohl-iso9660-archive-test-" +
                                 std::to_string(nonce) + "-" +
                                 std::to_string(attempt));
      error.clear();
      if (std::filesystem::create_directory(candidate, error)) {
        path_ = std::move(candidate);
        return;
      }
      if (error && error != std::errc::file_exists) {
        return;
      }
    }
  }

  ~TemporaryDirectory() {
    if (!path_.empty()) {
      std::error_code error;
      std::filesystem::remove_all(path_, error);
    }
  }

  TemporaryDirectory(const TemporaryDirectory&) = delete;
  TemporaryDirectory& operator=(const TemporaryDirectory&) = delete;

  [[nodiscard]] const std::filesystem::path& path() const noexcept {
    return path_;
  }

 private:
  std::filesystem::path path_;
};

[[nodiscard]] ohl::vfs::SharedMediaSource pin_image(
    const std::filesystem::path& path, const std::vector<std::byte>& image) {
  std::ofstream output{path, std::ios::binary};
  output.write(reinterpret_cast<const char*>(image.data()),
               static_cast<std::streamsize>(image.size()));
  output.close();
  if (!output.good()) {
    return nullptr;
  }
  auto opened = ohl::platform::open_media_source(path);
  return opened.valid() ? opened.source : nullptr;
}

[[nodiscard]] const DirectoryEntry* find_entry(
    const std::vector<DirectoryEntry>& entries, const std::string_view name) {
  const auto match = std::find_if(
      entries.begin(), entries.end(),
      [name](const DirectoryEntry& entry) { return entry.name == name; });
  return match == entries.end() ? nullptr : &*match;
}

[[nodiscard]] std::string read_all(ohl::vfs::Iso9660File& file) {
  std::vector<std::byte> buffer(static_cast<std::size_t>(file.size()));
  if (buffer.empty()) {
    return {};
  }
  const auto read = file.read(std::span{buffer});
  if (read < 0 || static_cast<std::uint64_t>(read) != file.size()) {
    return {};
  }
  std::string text;
  text.reserve(buffer.size());
  for (const auto value : buffer) {
    text.push_back(static_cast<char>(std::to_integer<unsigned char>(value)));
  }
  return text;
}

void test_joliet_tree(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "joliet.iso",
      ohl::media::test::make_synthetic_iso9660_image({}));
  check(source != nullptr, "pinned the Joliet fixture");
  if (source == nullptr) {
    return;
  }

  Iso9660Archive archive;
  check(archive.open(source) == VfsError::none, "mounted the Joliet fixture");
  check(archive.is_open(), "archive reports open");
  check(archive.uses_joliet(), "Joliet supplementary tree was selected");
  check(archive.volume_label() == "OHL SYNTHETIC", "Joliet volume label");

  const auto root = archive.list("/");
  check(root.error == VfsError::none, "listed the Joliet root");
  check(root.entries.size() == 2, "Joliet root entry count");
  const auto* const child = find_entry(
      root.entries, ohl::media::test::kIsoJolietDirectoryName);
  const auto* const sentinel = find_entry(
      root.entries, ohl::media::test::kIsoJolietSentinelName);
  check(child != nullptr && child->type == EntryType::directory,
        "Joliet subdirectory entry");
  check(sentinel != nullptr && sentinel->type == EntryType::file &&
            sentinel->size_bytes ==
                ohl::media::test::kIsoSentinelContents.size(),
        "Joliet file entry with the recorded size");

  const auto nested_listing = archive.list(
      std::string{"/"} +
      std::string{ohl::media::test::kIsoJolietDirectoryName});
  check(nested_listing.error == VfsError::none, "listed the Joliet subtree");
  check(nested_listing.entries.size() == 1, "Joliet subtree entry count");
  check(find_entry(nested_listing.entries,
                   ohl::media::test::kIsoJolietNestedName) != nullptr,
        "Joliet nested file entry");

  const auto nested_path =
      std::string{"/"} +
      std::string{ohl::media::test::kIsoJolietDirectoryName} + "/" +
      std::string{ohl::media::test::kIsoJolietNestedName};
  auto file = archive.open_file(nested_path);
  check(file != nullptr, "opened the Joliet nested file");
  if (file != nullptr) {
    check(file->size() == ohl::media::test::kIsoNestedContents.size(),
          "nested file size");
    check(read_all(*file) == ohl::media::test::kIsoNestedContents,
          "nested file contents");
    check(file->seek(5), "seek inside the nested file");
    check(file->tell() == 5, "tell after seek");
    check(!file->seek(file->size() + 1), "seek past the end is rejected");
  }
  auto relative = archive.open_file_at(
      std::string{"/"} +
          std::string{ohl::media::test::kIsoJolietDirectoryName},
      ohl::media::test::kIsoJolietNestedName);
  check(relative != nullptr, "opened the nested file relative to a directory");

  check(archive.open_file(
            std::string{"/"} +
            std::string{ohl::media::test::kIsoJolietDirectoryName}) == nullptr,
        "a directory cannot be opened as a file");
  check(archive.list("/does-not-exist").error == VfsError::not_found,
        "missing path reports not_found");
  check(archive.list("../escape").error == VfsError::invalid_path,
        "parent traversal is rejected");

  archive.close();
  check(!archive.is_open(), "closed archive reports not open");
  check(archive.list("/").error == VfsError::not_open,
        "listing a closed archive reports not_open");
}

void test_primary_tree(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "primary.iso",
      ohl::media::test::make_synthetic_iso9660_image({.joliet = false}));
  check(source != nullptr, "pinned the primary-only fixture");
  if (source == nullptr) {
    return;
  }

  Iso9660Archive archive;
  check(archive.open(source) == VfsError::none,
        "mounted the primary-only fixture");
  check(!archive.uses_joliet(), "primary tree was selected");

  const auto root = archive.list("/");
  check(root.error == VfsError::none, "listed the primary root");
  // The ";1" version suffix must be stripped from primary-tree identifiers.
  check(find_entry(root.entries,
                   ohl::media::test::kIsoPrimarySentinelName) != nullptr,
        "primary file entry without its version suffix");
  check(find_entry(root.entries,
                   ohl::media::test::kIsoPrimaryDirectoryName) != nullptr,
        "primary subdirectory entry");

  // Path lookup folds ASCII case, which primary-tree identifiers require.
  const auto lower = archive.list("/fixdir");
  check(lower.error == VfsError::none, "case-folded primary path lookup");
}

void test_rejected_structures(const std::filesystem::path& directory) {
  struct Case {
    std::string_view name;
    SyntheticIso9660Options options;
    VfsError expected;
    bool at_open{false};
  };
  const Case cases[] = {
      {.name = "block-size.iso",
       .options = {.logical_block_size = 512},
       .expected = VfsError::invalid_source,
       .at_open = true},
      {.name = "no-terminator.iso",
       .options = {.terminator = false},
       .expected = VfsError::invalid_source,
       .at_open = true},
      {.name = "volume-space.iso",
       .options = {.volume_space_too_large = true},
       .expected = VfsError::invalid_source,
       .at_open = true},
      {.name = "root-extent.iso",
       .options = {.root_extent_outside_volume = true},
       .expected = VfsError::invalid_source,
       .at_open = true},
      {.name = "file-extent.iso",
       .options = {.file_extent_outside_volume = true},
       .expected = VfsError::read_failed},
      {.name = "overlong-identifier.iso",
       .options = {.overlong_identifier = true},
       .expected = VfsError::read_failed},
      {.name = "multi-extent.iso",
       .options = {.multi_extent_file = true},
       .expected = VfsError::read_failed},
      {.name = "volume-sequence.iso",
       .options = {.file_record_volume_sequence = 2},
       .expected = VfsError::read_failed},
      {.name = "root-size.iso",
       .options = {.root_size_override = 100},
       .expected = VfsError::invalid_source,
       .at_open = true},
      {.name = "child-directory-size.iso",
       .options = {.child_directory_size_override = 100},
       .expected = VfsError::read_failed},
  };

  for (const auto& item : cases) {
    const auto source =
        pin_image(directory / item.name,
                  ohl::media::test::make_synthetic_iso9660_image(
                      item.options));
    check(source != nullptr, "pinned a rejected-structure fixture");
    if (source == nullptr) {
      continue;
    }
    Iso9660Archive archive;
    const auto opened = archive.open(source);
    if (item.at_open) {
      check(opened == item.expected, item.name);
      continue;
    }
    check(opened == VfsError::none, "mounted a record-level defect fixture");
    check(archive.list("/").error == item.expected, item.name);
  }
}

// A supplementary descriptor without a Joliet escape sequence must be skipped,
// not validated, so a defect in one never rejects the primary volume.
void test_non_joliet_supplementary(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "non-joliet-supplementary.iso",
      ohl::media::test::make_synthetic_iso9660_image({
          .joliet = false,
          .malformed_non_joliet_supplementary = true,
      }));
  check(source != nullptr, "pinned the non-Joliet supplementary fixture");
  if (source == nullptr) {
    return;
  }
  Iso9660Archive archive;
  check(archive.open(source) == VfsError::none,
        "a malformed non-Joliet supplementary descriptor is skipped");
  check(!archive.uses_joliet(), "the primary tree is used");
  const auto root = archive.list("/");
  check(root.error == VfsError::none && root.entries.size() == 2,
        "the primary tree still lists");
}

// Joliet identifiers preserve case, so siblings differing only in case are
// distinct entries and must resolve independently.
void test_joliet_case_sensitivity(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "joliet-case.iso",
      ohl::media::test::make_synthetic_iso9660_image({
          .joliet_case_siblings = true,
      }));
  check(source != nullptr, "pinned the Joliet case fixture");
  if (source == nullptr) {
    return;
  }
  Iso9660Archive archive;
  check(archive.open(source) == VfsError::none,
        "mounted the Joliet case fixture");
  const auto upper = archive.open_file("/CaseName.txt");
  const auto lower = archive.open_file("/casename.txt");
  check(upper != nullptr && lower != nullptr,
        "both case-distinct Joliet siblings resolve");
  if (upper != nullptr && lower != nullptr) {
    check(upper->size() == 8 && lower->size() == 9,
          "case-distinct Joliet siblings resolve to different records");
  }
  check(archive.open_file("/CASENAME.TXT") == nullptr,
        "Joliet lookups are not case folded");
}

void test_directory_cycle(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "cycle.iso",
      ohl::media::test::make_synthetic_iso9660_image({
          .directory_cycle = true,
      }));
  check(source != nullptr, "pinned the cycle fixture");
  if (source == nullptr) {
    return;
  }
  Iso9660Archive archive;
  check(archive.open(source) == VfsError::none, "mounted the cycle fixture");
  const auto looped = archive.list(
      std::string{"/"} +
      std::string{ohl::media::test::kIsoJolietDirectoryName} + "/" +
      std::string{ohl::media::test::kIsoJolietLoopName});
  check(looped.error == VfsError::invalid_source,
        "a directory extent cycle is rejected");
}

void test_paging(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "paged.iso",
      ohl::media::test::make_synthetic_iso9660_image({
          .extra_root_files = 6,
      }));
  check(source != nullptr, "pinned the paging fixture");
  if (source == nullptr) {
    return;
  }

  UdfArchiveLimits limits;
  limits.directory.max_page_entries = 2;
  Iso9660Archive archive;
  check(archive.open(source, limits) == VfsError::none,
        "mounted the paging fixture");

  auto page = archive.list_page("/");
  check(page.error == VfsError::none, "first page succeeded");
  check(page.entries.size() == 2, "first page honours max_page_entries");
  check(!page.complete(), "first page reports another page");

  std::size_t total = page.entries.size();
  while (!page.complete()) {
    page = archive.continue_list(std::move(page.cursor));
    check(page.error == VfsError::none, "continuation page succeeded");
    if (page.error != VfsError::none) {
      return;
    }
    total += page.entries.size();
  }
  check(total == 8, "paged enumeration returned every entry");

  const auto complete = archive.list("/");
  check(complete.error == VfsError::none, "compatibility list succeeded");
  check(complete.entries.size() == 8, "compatibility list entry count");

  // A cursor from one archive is never accepted by an unrelated archive.
  Iso9660Archive other;
  check(other.open(source, limits) == VfsError::none, "second mount");
  auto foreign = archive.list_page("/");
  check(other.continue_list(std::move(foreign.cursor)).error ==
            VfsError::invalid_cursor,
        "foreign cursors are rejected");
}

void test_media_archive_facade(const std::filesystem::path& directory) {
  const auto source = pin_image(
      directory / "facade.iso",
      ohl::media::test::make_synthetic_iso9660_image({}));
  check(source != nullptr, "pinned the facade fixture");
  if (source == nullptr) {
    return;
  }

  MediaArchive archive;
  check(archive.open(MediaFormat::iso9660, source) == VfsError::none,
        "facade mounted an ECMA-119 image");
  check(archive.format() == MediaFormat::iso9660, "facade reports the class");
  check(archive.is_open(), "facade reports open");
  check(archive.volume_label() == "OHL SYNTHETIC", "facade volume label");
  const auto root = archive.list("/");
  check(root.error == VfsError::none && root.entries.size() == 2,
        "facade listed the root");

  auto file = archive.open_file(
      std::string{"/"} + std::string{ohl::media::test::kIsoJolietSentinelName});
  check(file != nullptr, "facade opened a file");
  if (file != nullptr) {
    check(file->size() == ohl::media::test::kIsoSentinelContents.size(),
          "facade file size");
    check(file->tell() == 0, "facade file starts at the beginning");
  }

  const auto shared = archive.share();
  check(shared.is_open() && shared.format() == MediaFormat::iso9660,
        "facade share keeps the mounted state");

  // A UDF-classified mount of an ECMA-119 image must not silently succeed.
  MediaArchive misclassified;
  check(misclassified.open(MediaFormat::udf, source) != VfsError::none,
        "facade does not mount an ECMA-119 image as UDF");
}

}  // namespace

int main() {
  const TemporaryDirectory directory;
  if (directory.path().empty()) {
    std::cerr << "failed to create a temporary directory\n";
    return 1;
  }

  test_joliet_tree(directory.path());
  test_primary_tree(directory.path());
  test_rejected_structures(directory.path());
  test_non_joliet_supplementary(directory.path());
  test_joliet_case_sensitivity(directory.path());
  test_directory_cycle(directory.path());
  test_paging(directory.path());
  test_media_archive_facade(directory.path());

  return failures == 0 ? 0 : 1;
}
