[workspace]

[package]
name = "ohl-formats-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.ohl-formats]
path = ".."
features = ["test-support"]

[[bin]]
name = "bsp30_fuzz"
path = "fuzz_targets/bsp30_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "wad3_fuzz"
path = "fuzz_targets/wad3_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mdl10_fuzz"
path = "fuzz_targets/mdl10_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "spr_fuzz"
path = "fuzz_targets/spr_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "titles_fuzz"
path = "fuzz_targets/titles_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sentences_fuzz"
path = "fuzz_targets/sentences_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "skill_cfg_fuzz"
path = "fuzz_targets/skill_cfg_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "liblist_fuzz"
path = "fuzz_targets/liblist_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hud_sprites_fuzz"
path = "fuzz_targets/hud_sprites_fuzz.rs"
test = false
doc = false
bench = false
