//! Shared synthetic-media helpers.
//!
//! Every fixture here is project-authored filler generated by a fixed
//! arithmetic rule. Nothing in this directory is derived from real media, and
//! no test in this crate reads any.

#![allow(dead_code, reason = "each integration test binary uses a subset")]

use std::path::Path;
use std::sync::Arc;

use ohl_media::{MediaClass, MediaDescription, MediaDigest, ValidatedMedia, VolumeLabel};
use ohl_platform::MediaSource;

/// Deterministic project-authored filler bytes.
#[must_use]
pub fn synthetic_bytes(length: usize) -> Vec<u8> {
    (0..length)
        .map(|index| u8::try_from((index * 31 + 7) % 251).unwrap_or(0))
        .collect()
}

/// Writes `content` into `directory` under a fixed name and pins it.
pub fn pinned_source(directory: &Path, name: &str, content: &[u8]) -> Arc<MediaSource> {
    let path = directory.join(name);
    std::fs::write(&path, content).expect("synthetic fixture");
    Arc::new(MediaSource::open(&path).expect("pinned source"))
}

/// A description with a fixed class, filesystem name and label.
#[must_use]
pub fn description() -> MediaDescription {
    MediaDescription::new(MediaClass::Udf, "udf", VolumeLabel::sanitized("SYNTHETIC"))
}

/// Fingerprints `source` and binds the proof.
pub fn validated(source: Arc<MediaSource>) -> ValidatedMedia {
    ValidatedMedia::fingerprinting(source, description()).expect("stable synthetic source")
}

/// The SHA-256 of `bytes`, for cross-checking against `ohl-core`.
#[must_use]
pub fn expected_digest(bytes: &[u8]) -> MediaDigest {
    MediaDigest::from_bytes(ohl_core::StreamingSha256::digest(bytes))
}
