//! Shared synthetic-media helpers.
//!
//! Every fixture here is project-authored filler generated by a fixed
//! arithmetic rule. Nothing in this directory is derived from real media, and
//! no test in this crate reads any.

#![allow(dead_code, reason = "each integration test binary uses a subset")]

use std::path::Path;
use std::sync::Arc;

use ohl_media::{MediaClass, MediaDescription, MediaDigest, ValidatedMedia, VolumeLabel};
use ohl_platform::MediaSource;

/// Deterministic project-authored filler bytes.
#[must_use]
pub fn synthetic_bytes(length: usize) -> Vec<u8> {
    (0..length)
        .map(|index| u8::try_from((index * 31 + 7) % 251).unwrap_or(0))
        .collect()
}

/// Writes `content` into `directory` under a fixed name and pins it.
pub fn pinned_source(directory: &Path, name: &str, content: &[u8]) -> Arc<MediaSource> {
    let path = directory.join(name);
    std::fs::write(&path, content).expect("synthetic fixture");
    Arc::new(MediaSource::open(&path).expect("pinned source"))
}

/// A description with a fixed class, filesystem name and label.
#[must_use]
pub fn description() -> MediaDescription {
    MediaDescription::new(MediaClass::Udf, "udf", VolumeLabel::sanitized("SYNTHETIC"))
}

/// Fingerprints `source` and binds the proof.
pub fn validated(source: Arc<MediaSource>) -> ValidatedMedia {
    ValidatedMedia::fingerprinting(source, description()).expect("stable synthetic source")
}

/// The SHA-256 of `bytes`, for cross-checking against `ohl-core`.
#[must_use]
pub fn expected_digest(bytes: &[u8]) -> MediaDigest {
    MediaDigest::from_bytes(ohl_core::StreamingSha256::digest(bytes))
}

/// A temporary directory whose path has been fully resolved.
///
/// macOS puts `TMPDIR` under `/var`, which is itself a symbolic link to
/// `/private/var`. The cache's directory-tree check never follows a link, so
/// a layout rooted at the unresolved path is correctly refused as unsafe.
/// Resolving the root once here is what the C++ test did with
/// `std::filesystem::canonical`, and it keeps the check under test rather
/// than the platform's temporary-directory spelling.
pub struct TemporaryRoot {
    directory: tempfile::TempDir,
    path: std::path::PathBuf,
}

impl TemporaryRoot {
    /// Creates and resolves a temporary directory.
    #[must_use]
    pub fn new() -> Self {
        let directory = tempfile::tempdir().expect("temporary directory");
        let path = std::fs::canonicalize(directory.path()).expect("resolved temporary directory");
        Self { directory, path }
    }

    /// The resolved root path.
    #[must_use]
    pub fn path(&self) -> &Path {
        debug_assert!(self.directory.path().exists());
        &self.path
    }
}

impl Default for TemporaryRoot {
    fn default() -> Self {
        Self::new()
    }
}
